### PR TITLE
templates: Add Sokol - eCommerce Template

### PR DESCRIPTION
**Pull request by cesswhite**
Step into the world of Sokol, where simplicity meets power in e-commerce templates, all thanks to [Nuxt](https://ui.nuxt.com/) and [Nuxt UI](https://ui.nuxt.com/).

Designed with small startups in mind, Sokol empowers you to scale your own service or platform effortlessly, or seamlessly transition from another provider. With Sokol, you're not just getting a template – you're gaining full control over your store's source code and styles.

Demo here: https://sokol.vercel.app/

cover

### CODE REVIEW

**Comment by Atinux** [comment]
You purchase link goes to the test mode of LemonSqueezy:

**Comment by cesswhite** [comment]
Yes, I am still waiting for the activation of my store from their support.

**Comment by cesswhite** [comment]
@Atinux Hi, while waiting for the validation of my store in lemon squeezy, I generated a new link in Gumroad, and I updated the template, I hope you can check it, thank you very much.

**Comment by Atinux** [comment]
I rather wait for LemonSqueezy to be ready, no rush :)

Once ready, would you please enable the affiliate for your store? We usually list premium template on the website with an affiliate link so it provide a form of revenue to maintain the open source framework.

**Comment by cesswhite** [comment]
Sure, with pleasure. I will keep this PR updated,
Thank you

**Pull request closed without merging**
