### PR TITLE
feat: add current Nuxt version to header

### PR DESCRIPTION
**Pull request by IsraelOrtuno**
This little PR adds the current Nuxt version right to the header. I find this really useful as docs are visited very often by devs of any level and this is really useful to discover patch releases.

Despite I have tried to design it as soft as possible (but readable) I am aware this may be a little bit intrusive. Open to any feedback from the design team and maybe put it in a tooltip (show only on hover) or maybe somewhere else (docs sidebar sounds right too).

It also exposes a `/api/release.json` endpoint which returns the latest version and maybe some other useful meta information in the future.

Screenshot 2024-04-08 at 19 46 48
Screenshot 2024-04-08 at 19 46 53

### CODE REVIEW

**Comment by Atinux** [comment]
Not sure if I want to have it in the header though 🤔 

What do you think @benjamincanac ?

**Comment by benjamincanac** [comment]
I'm not sure either where to put this but maybe we could use a badge to display it? Like https://ui.nuxt.com/dev/getting-started

**Comment by Atinux** [comment]
Badge like Nuxt UI could be nice.

I would also avoid having the patch version (ex: `v3.11`)

**Comment by IsraelOrtuno** [comment]
> Badge like Nuxt UI could be nice.
> 
> I would also avoid having the patch version (ex: `v3.11`)

We could add the patch version on a tooltip on hover. Will update the PR with the badge soon.

**Comment by IsraelOrtuno** [comment]
Way cleaner with badge and tooltip:

Screenshot 2024-04-16 at 11 40 21
Screenshot 2024-04-16 at 11 40 24
Screenshot 2024-04-16 at 11 40 28

**Comment by Atinux** [comment]
Thanks @IsraelOrtuno !

I updated the Nuxt API to return the version: https://api.nuxt.com/stats

This way we can directly use `useStats()`.

I simplified your code and merging now!

**Comment by IsraelOrtuno** [comment]
Didn't know about `useStats` composable, way cleaner!

**Pull request merged**
