### PR TITLE
refactor: migrate to `compatibilityVersion: 4`

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

this slightly improves perf and should enable us to test a bit better

~~**TODO**: seemingly font files aren't detected/loaded - needs investigation~~ this was due to having `tailwind.config.ts` in `app/` and not in the root directory

### CODE REVIEW

**Comment by atinux** [comment]
Seems we have some styling issues in production 
CleanShot 2024-10-21 at 14 53 28@2x

**Comment by danielroe** [comment]
The issue with fonts was related to having `tailwind.config.ts` in `app/` rather than rootDir - could this be similar?

**Comment by benjamincanac** [comment]
Should be good now! 😊

**Comment by danielroe** [comment]
you star ❤️

**Pull request merged**
