### PR TITLE
feat(templates): Add Shadcn Landing Pro Template

### PR DESCRIPTION
**Pull request by magweter**
Added the [Nuxt 3 Shadcn Landing Pro](https://nuxt-shadcn-landing-pro.vercel.app/) template. A SaaS landingpage starter for developers wanting to get up and running quickly with their project. Built fully with the Vue ported Shadcn components. 

Thanks for the amazing work being done with Nuxt 3! Been using it since beta 🫶🏻

shadcn-landing-pro

### CODE REVIEW

**Comment by Atinux** [comment]
I usually list premium template with a partnership link, could you enable LemonSqueezy affiliates @magweter ?

**Comment by magweter** [comment]
@Atinux of course, no problem at all. I have enabled my affiliate hub and added the affiliate tag `aff=J0Emk` I saw in other purchase links.

**Comment by Atinux** [comment]
Submitted a request for affiliate, once you approve I will update the purchase link with the correct affiliate link :)

**Comment by magweter** [comment]
@Atinux I have approved and the status is active so we should be good to go :) 

image

**Pull request merged**
