### PR TITLE
fix(blog): refactor OG Image URL

### LINKED ISSUE #1625: docs(blog): The image is not displayed
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Some images were not displayed on the blog below.

- https://nuxt.com/blog/new-website#open-graph-images

image

When I checked the cause, it seemed that the definition method of MDC was different.

### PR DESCRIPTION
**Pull request by shinGangan**
### 🔗 Linked issue

closed #1625 .

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

~~When I checked the cause, it seemed that the definition method of MDC was different.~~

The setting method of OG Image URL has changed from V3.

- ref: https://nuxtseo.com/og-image/releases/v3#new-og-image-url

### CODE REVIEW

**Comment by shinGangan** [comment]
Please review when the reviewer has a time 🙏

**Comment by benjamincanac** [comment]
@shinGangan It's still broken for me in the preview: https://nuxt-website-o5aumb001-nuxt-js.vercel.app/blog/new-website

**Comment by shinGangan** [comment]
If you look at the target image path, it looks like a path that does not exist. `/docs/getting-started/installation/__og_image__/og.png`

I checked the commit where the fixed part was added, but it seems that the image has not been added at this commit.

- https://github.com/nuxt/nuxt.com/commit/8986b5737a63a7a148fb021356af6663ecdc666c

**Comment by shinGangan** [comment]
Add an image in this PR.

**Comment by Flosciante** [comment]
hi @shinGangan, thx for contribution, i deployed and it seems it's still broken on the preview [https://nuxt-website-i2o3lknwi-nuxt-js.vercel.app/blog/new-website#open-graph-images](url)

**Comment by Flosciante** [comment]
Nice work @shinGangan thx for the fix

**Comment by shinGangan** [comment]
@Flosciante , thnaks for merged 🙏

**Pull request merged**
