### PR TITLE
feat(templates): Added vuexy admin template

### PR DESCRIPTION
**Pull request by jd-solanki**
banner
**Vuexy is the best selling admin template for VueJS since launch**

[Item Page](https://themeforest.net/item/vuexy-vuejs-html-laravel-admin-dashboard-template/23328599)

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @jd-solanki 

I saw it but then I did not see any demo using Nuxt actually

**Comment by jd-solanki** [comment]
Hi @Atinux,

I discussed to the team about the nuxt demo. We'll deploy the nuxt demo in couple of days for the preview. In meantime, I'm converting this PR to the draft.

Thanks for your attention.

**Comment by jd-solanki** [comment]
Hi @Atinux 👋🏻

I've updated the PR as per the latest deployment and implemented the demos using Nuxt. Here are a few notes:

* I've added both free and premium templates to represent them separately
* I've included the URL of the HTML demo in the premium version, as providing a link to the Nuxt demo for the screenshot might result in a screenshot of the login page due to redirection (as per real-world flow).

Please let me know if there's anything else I need to address. I'm eager to view the materio template on the Nuxt site.

**Comment by jd-solanki** [comment]
Hi @Atinux 

Sorry for the ping but I noticed there were couple of addition in the same file I made PR on and those results in file conflicts and also delays the merge of the PR.

Can you please let me know what I'm missing here.

Keep on the good work 😇

**Comment by Atinux** [comment]
Sorry for the delay, it's good now 🚀

**Pull request merged**
